# Site settings
baseurl = "http://thaissa.me/sebo/"
languageCode = "en-us"
title = "Sebo da Thaíssa"
theme = "hugrid"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Sebo da Thaíssa"
    subtitle = "Livros de informática, engenharia e outros"

    # Body background color
    bodybgcolor = "#ffe1e6"

    # Footer text
    footertext = "Made by [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/), [Hugo](http://gohugo.io) and [me](https://github.com/aerohub)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
